#Política de Privacidad
De acuerdo a la Ley Orgánica 15/1999, de 13 de Diciembre, de Protección de Datos de Carácter Personal (LOPD), se informa a los usuarios que los datos personales que en algún momento se nos hagan llegar a través del formulario de contacto y del registro de usuario, así como cualesquiera otros que se introduzcan en la web serán incorporados a los ficheros registrados en la Agencia Española de Protección de Datos, propiedad y responsabilidad de #### Asolear ####  , con domicilio social jhfdaslfhka rwerqw , con la finalidad de gestionar las comunicaciones necesarias con los usuarios así como la formalización del registro en este sitio web. Igualmente le informamos de la posibilidad de utilizar sus datos de contacto para mantenerle informado con boletines, promociones y/o ofertas que puedan ser de su interés relacionados con nuestra actividad. A tal efecto, y de conformidad con el Real Decreto 1720/2007, de 21 de Diciembre, Asociación Autónoma de Instaladores Eléctricos y de Telecomunicaciones de Granada (AAIE), adoptará las medidas de seguridad adecuadas a los datos personales que los usuarios faciliten y pondremos los medios y medidas técnicas para evitar la pérdida, mal uso, alteración, acceso no autorizado y robo de los mismos. Sus datos personales no serán cedidos a ninguna tercera persona, empresa o entidad, salvo aquellos que por obligaciones legales, así haya que hacerlo.Respecto a la publicación de datos personales en blogs y redes sociales que puede compartir esta web, la política de privacidad es la marcada por las entidades responsables de esos sitios así como la aquí recogida. #### Asolear ####  no se hace responsable de la información personal que cada usuario pueda publicar. El usuario podrá ejercitar en todo momento los derechos de acceso, rectificación, oposición y cancelación de sus datos personales, de conformidad con lo establecido en la normativa vigente sobre protección de datos personales, dirigiéndose a nuestra empresa por escrito postal o vía e-mail, adjuntando copia del Documento Nacional de Identidad.



### Condiciones de Uso

# INFORMACIÓN GENERAL

El presente sitio web tiene por objeto la prestación de servicios de información y documentación así como la intermediación en actividades y servicios para las empresas pertenecientes a las Asociaciones de Instaladores de Granada. En el caso de productos o servicios que sean prestados por terceros, no se achacará responsabilidad alguna a las Asociaciones intermediarias por posibles deficiencias en los servicios o información ofrecida.INFORMACIÓN ACERCA DE LA CLAVE PERSONAL DE ACCESO

La clave de acceso es personal e intransferible, compuesta por una dirección de email y una contraseña (password) para poder visitar zonas de uso restringido, los usuarios serán los únicos que podrán hacer uso del mismo y, en consecuencia, se responsabilizarán por todas las operaciones realizadas con dicha clave.Facilitar, usar, intentar descifrar la clave de acceso de otros o desvelarla a otras personas no autorizadas, es considerado como una grave violación de las normas de utilización y seguridad. Si el usuario tuviera razones para creer que su clave es o puede ser conocida por alguna persona no autorizada para ello, deberá modificar la misma.Igualmente, en cualquier momento se podrá dar de baja en la cuenta de acceso personal, poniéndose en contacto con los prestadores a través de correo electrónico, info@instaladoresgranada.com, notificando baja de la cuenta.SOBRE LOS PRODUCTOS

El acceso a la página se realiza en un entorno seguro. La responsabilidad por los productos o servicios ofrecidos en el portal por terceras personas o entidades corresponde exclusivamente a éstas. Los prestadores, en ningún caso asumen el riesgo y ventura de las operaciones y relaciones entre el usuario y las personas o entidades mencionadas.VALIDEZ

Si por cualquier disposición legal o declaración judicial alguna de las normas contenidas en estos apartados no se ajustase a Derecho, ello no obstará para que el resto de los términos y condiciones no afectados se consideren válidos a todos los efectos.